version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mynetwork

  spring-app:
    image: shop
    container_name: spring-app-container
    ports:
      - "8081:8081"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
